name: CI

on:
  push:
    branches: [ master ]

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: docker://node:10-alpine
        name: Setup Node

      - name: Install dependencies
        working-directory: _tools
        run: npm install

      - name: Assemble and pack
        working-directory: _tools
        run: npx gulp

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: "latest"
          files: _tools/build/*.zip
